#https://github.com/gohugoio/hugo/blob/master/snap/snapcraft.yaml
---
name: tenv
summary: Version manager for OpenTofu, Terraform and Terragrunt, written in Go.
description: |
  tenv is a versatile version manager for [OpenTofu](https://opentofu.org), [Terraform](https://www.terraform.io/) and [Terragrunt](https://terragrunt.gruntwork.io/),
  written in Go. Our tool simplifies the complexity of handling different versions of these powerful tools,
  ensuring developers and DevOps professionals can focus on what matters most - building and deploying efficiently.

  tenv is a successor of [tofuenv](https://github.com/tofuutils/tofuenv) and [tfenv](https://github.com/tfutils/tfenv).
adopt-info: tenv
version: git
base: core22
confinement: devmode #strict
parts:
  git:
    plugin: nil
    stage-packages:
      - git
    prime:
      - usr/bin/git
      - usr/lib
  go:
    plugin: nil
    stage-snaps:
      - go/1.22/stable
    prime:
      - bin/go
      - pkg/tool
      - -pkg/tool/*

  tenv:
    plugin: nil
    source: .
    after:
      - git
      - go
    override-build: |
      export CGO_ENABLED=0
      export CGO_LDFLAGS_ALLOW=".*"
      
      go mod tidy
      go test ./...
      go get -u ./cmd/tenv
      go get -u ./cmd/tofu
      go get -u ./cmd/terraform
      go get -u ./cmd/terragrunt
      go get -u ./cmd/tf
      go build -v -s -w -X main.version={{.Tag}}
      
      snapcraftctl build
      

apps:
  tenv:
    command: cmd/tenv
    plugs:
      - home
      - network-bind
      - removable-media
      - etc-gitconfig
      - gitconfig
      - ssh-keys

grade: devel #stable
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

#plugs:
#  dot-config-woke:
#    interface: personal-files
#    read:
#      - $HOME/.config/woke.yaml
#      - $HOME/.config/woke.yml
#      - $HOME/.woke.yaml
#      - $HOME/.woke.yml
