---
name: "Snapcraft Release Pipeline"

on:
#  release:
#    types: [released]
  push:
    branches:
      - 'feat/add-snap-support'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: build

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge

#      - uses: snapcore/action-publish@v1
#        with:
#          store_login: ${{ secrets.STORE_LOGIN }}
#          snap: ${{ steps.build.outputs.snap }}
#          release: edge